"""empty message

Revision ID: 3bd5c53f4f8c
Revises: be3e10557ca3
Create Date: 2018-03-18 23:23:20.923000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3bd5c53f4f8c'
down_revision = 'be3e10557ca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('patient_chemo', sa.Column('mdtc', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'patient_chemo', 'patient_info', ['mdtc'], ['mdtc'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patient_chemo', type_='foreignkey')
    op.drop_column('patient_chemo', 'mdtc')
    op.alter_column('employees', 'is_admin',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    # ### end Alembic commands ###
