"""empty message

Revision ID: 50e40d0b2ad9
Revises: 
Create Date: 2018-03-18 22:20:16.877000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e40d0b2ad9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_first_name'), 'employees', ['first_name'], unique=False)
    op.create_index(op.f('ix_employees_last_name'), 'employees', ['last_name'], unique=False)
    op.create_index(op.f('ix_employees_username'), 'employees', ['username'], unique=True)
    op.create_table('patient_info',
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('mdtc', sa.String(length=60), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=7), nullable=True),
    sa.Column('phone_no', sa.Integer(), nullable=True),
    sa.Column('diagnosis', sa.String(length=60), nullable=True),
    sa.Column('symptoms', sa.String(length=400), nullable=True),
    sa.Column('histopathology', sa.String(length=400), nullable=True),
    sa.Column('ihc', sa.String(length=400), nullable=True),
    sa.Column('genetic_mutation', sa.String(length=400), nullable=True),
    sa.Column('ct_scan', sa.String(length=400), nullable=True),
    sa.Column('wpet', sa.String(length=400), nullable=True),
    sa.Column('ugie', sa.String(length=400), nullable=True),
    sa.Column('colonoscopy', sa.String(length=400), nullable=True),
    sa.Column('mri', sa.String(length=400), nullable=True),
    sa.Column('other_investigation', sa.String(length=400), nullable=True),
    sa.Column('remarks', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('mdtc')
    )
    op.create_table('patient_chemo',
    sa.Column('chemo_id', sa.Integer(), nullable=False),
    sa.Column('mdtc', sa.String(length=60), nullable=True),
    sa.Column('cycle', sa.String(length=90), nullable=True),
    sa.Column('chemotherapy', sa.String(length=1000), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('response', sa.String(length=1000), nullable=True),
    sa.Column('side_effect', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['mdtc'], ['patient_info.mdtc'], ),
    sa.PrimaryKeyConstraint('chemo_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_chemo')
    op.drop_table('patient_info')
    op.drop_index(op.f('ix_employees_username'), table_name='employees')
    op.drop_index(op.f('ix_employees_last_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_first_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
