"""empty message

Revision ID: 5a203c27a5d8
Revises: 3bd5c53f4f8c
Create Date: 2018-03-18 23:26:16.252000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a203c27a5d8'
down_revision = '3bd5c53f4f8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('patient_chemo', 'cycle',
               existing_type=mysql.VARCHAR(length=90),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient_chemo', 'cycle',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=90),
               existing_nullable=True)
    op.alter_column('employees', 'is_admin',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    # ### end Alembic commands ###
