"""empty message

Revision ID: be3e10557ca3
Revises: 50e40d0b2ad9
Create Date: 2018-03-18 23:22:51.959000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be3e10557ca3'
down_revision = '50e40d0b2ad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.drop_constraint(u'patient_chemo_ibfk_1', 'patient_chemo', type_='foreignkey')
    op.drop_column('patient_chemo', 'mdtc')
    op.alter_column('patient_info', 'mdtc',
               existing_type=mysql.VARCHAR(length=60),
               type_=sa.Integer(),
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient_info', 'mdtc',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=60),
               autoincrement=True)
    op.add_column('patient_chemo', sa.Column('mdtc', mysql.VARCHAR(length=60), nullable=True))
    op.create_foreign_key(u'patient_chemo_ibfk_1', 'patient_chemo', 'patient_info', ['mdtc'], ['mdtc'])
    op.alter_column('employees', 'is_admin',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    # ### end Alembic commands ###
